Repository CodeJoustHQ/main, pull requests merged in 2020-11, with the labels that each got.

#71 Add difficulty to problem classes and endpoints
  src/main/java/com/rocketden/main/dto/problem/CreateProblemRequest.java
  src/main/java/com/rocketden/main/dto/problem/ProblemDto.java
  src/main/java/com/rocketden/main/exception/ProblemError.java
  src/main/java/com/rocketden/main/exception/api/ApiExceptionHandler.java
  src/main/java/com/rocketden/main/model/problem/Problem.java
  src/main/java/com/rocketden/main/model/problem/ProblemDifficulty.java
  src/main/java/com/rocketden/main/service/ProblemService.java
  src/test/java/com/rocketden/main/api/ProblemTests.java
  src/test/java/com/rocketden/main/api/RoomTests.java
  src/test/java/com/rocketden/main/mapper/ProblemMapperTests.java
  src/test/java/com/rocketden/main/service/ProblemServiceTests.java
Labels: backend

#70 User can be kicked from room
  frontend/src/api/Room.ts
  frontend/src/components/card/HostActionCard.tsx
  frontend/src/views/Lobby.tsx
  src/main/java/com/rocketden/main/controller/v1/RoomController.java
  src/main/java/com/rocketden/main/dto/room/RemoveUserRequest.java
  src/main/java/com/rocketden/main/dto/user/DeleteUserRequest.java
  src/main/java/com/rocketden/main/exception/UserError.java
  src/main/java/com/rocketden/main/model/Room.java
  src/main/java/com/rocketden/main/service/RoomService.java
  src/main/java/com/rocketden/main/service/UserService.java
  src/main/java/com/rocketden/main/socket/WebSocketConnectionEvents.java
  src/test/java/com/rocketden/main/api/RoomTests.java
  src/test/java/com/rocketden/main/api/UserTests.java
  src/test/java/com/rocketden/main/service/RoomServiceTests.java
  src/test/java/com/rocketden/main/service/UserServiceTests.java
  src/test/java/com/rocketden/main/socket/RoomSocketTests.java
Labels: backend, frontend

#73 Add console panel to game page
  frontend/src/api/Problem.ts
  frontend/src/components/core/Button.tsx
  frontend/src/components/core/Container.tsx
  frontend/src/components/core/Input.tsx
  frontend/src/components/core/Text.tsx
  frontend/src/components/game/Console.tsx
  frontend/src/components/game/Editor.tsx
  frontend/src/components/layout/Main.tsx
  frontend/src/views/Game.tsx
Labels: frontend

#76 Add test for conditional room host update method
  src/test/java/com/rocketden/main/service/RoomServiceTests.java
Labels: backend

#74 Create client-facing problemId field and random problem endpoint
  frontend/src/api/Problem.ts
  frontend/src/views/Game.tsx
  frontend/src/views/Lobby.tsx
  src/main/java/com/rocketden/main/controller/v1/ProblemController.java
  src/main/java/com/rocketden/main/dao/ProblemRepository.java
  src/main/java/com/rocketden/main/dto/problem/ProblemDto.java
  src/main/java/com/rocketden/main/dto/problem/ProblemSettingsDto.java
  src/main/java/com/rocketden/main/exception/ProblemError.java
  src/main/java/com/rocketden/main/model/problem/Problem.java
  src/main/java/com/rocketden/main/service/ProblemService.java
  src/test/java/com/rocketden/main/api/ProblemTests.java
  src/test/java/com/rocketden/main/entity/ProblemEntityTests.java
  src/test/java/com/rocketden/main/mapper/ProblemMapperTests.java
  src/test/java/com/rocketden/main/service/ProblemServiceTests.java
Labels: backend

#75 Create the basis for the game backend.
  src/main/java/com/rocketden/main/dto/game/GameDto.java
  src/main/java/com/rocketden/main/dto/game/PlayerCodeDto.java
  src/main/java/com/rocketden/main/dto/game/PlayerDto.java
  src/main/java/com/rocketden/main/dto/game/SubmissionDto.java
  src/main/java/com/rocketden/main/dto/game/TimerDto.java
  src/main/java/com/rocketden/main/dto/notification/NotificationDto.java
  src/main/java/com/rocketden/main/exception/GameError.java
  src/main/java/com/rocketden/main/game_object/CodeLanguage.java
  src/main/java/com/rocketden/main/game_object/Game.java
  src/main/java/com/rocketden/main/game_object/GameNotification.java
  src/main/java/com/rocketden/main/game_object/Player.java
  src/main/java/com/rocketden/main/game_object/PlayerCode.java
  src/main/java/com/rocketden/main/game_object/Submission.java
  src/main/java/com/rocketden/main/game_object/Timer.java
  src/main/java/com/rocketden/main/service/GameManagementService.java
  src/main/java/com/rocketden/main/service/GameService.java
  src/main/java/com/rocketden/main/service/LiveGameService.java
  src/main/java/com/rocketden/main/service/NotificationService.java
  src/main/java/com/rocketden/main/service/SubmitService.java
Labels: backend
